#!/usr/bin/env python3
"""Builds the embedding guide for newspapers in the six languages of Hiku, from one template.

    python3 tools/build_guide.py

Writes daily/embed.html (Norwegian) and daily/embed-<lang>.html for the others. Change BASE when the site moves to
its own domain; every address in the guides follows it.
"""
import html
import pathlib

# Where the game is served from. The embed script works out its own address, so snippets already pasted keep
# working wherever they point, as long as that host still serves the files.
BASE = "https://hikupuzzle.com/daily/"
HOST = "https://hikupuzzle.com"
HOST_NAME = "Cloudflare"
APP = "https://apps.apple.com/app/apple-store/id6816387508?pt=121709952&amp;ct=web-guide&amp;mt=8"

LANGS = ["nb", "en", "sv", "da", "fi", "de"]
FILE = {l: ("embed.html" if l == "nb" else f"embed-{l}.html") for l in LANGS}
NATIVE = {"nb": "Norsk", "en": "English", "sv": "Svenska", "da": "Dansk", "fi": "Suomi", "de": "Deutsch"}
GAME_TITLE = {"nb": "Dagens Hiku", "en": "Daily Hiku", "sv": "Dagens Hiku", "da": "Dagens Hiku", "fi": "Päivän Hiku", "de": "Hiku des Tages"}

T = {
"nb": dict(
  title="Dagens Hiku på din nettside",
  description="Slik bygger du inn Dagens Hiku, et daglig tallspill, på en nettavis eller nettside: to linjer kode, ingen informasjonskapsler.",
  lead="Dagens Hiku er et rolig tallspill med fire nye brett hver dag, fra lett til ekspert. Det er gratis å bygge inn på en nettavis eller nettside, med to linjer kode.",
  rule="Regelen er kort: tallet sier hvor langt det hopper, vannrett eller loddrett. Lander det på et annet tall, trekkes de fra hverandre. Målet er å få alle tallene til å forsvinne. Brettene er de samme som i Hiku-appen for iPhone.",
  how="Slik gjør du",
  step1="Lim inn koden under der spillet skal stå, for eksempel i en artikkel eller på en egen spillside.",
  step2="Publiser. Spillet henter dagens brett selv og tilpasser høyden sin.",
  once="Skriptet trenger bare å stå én gang per side, selv om du har flere spill på samme side.",
  try_="Prøv og kopier",
  try_lead="Velg innstillingene, se spillet endre seg, og kopier koden når dere er fornøyde.",
  f_lang="Språk", f_lang_page="Sidens eget språk",
  lang_names=dict(nb="Norsk", en="Engelsk", sv="Svensk", da="Dansk", fi="Finsk", de="Tysk"),
  f_theme="Farger", f_theme_auto="Følg leseren", f_theme_light="Alltid lyst", f_theme_dark="Alltid mørkt",
  f_level="Første brett", f_level_last="Leserens forrige nivå",
  levels=dict(easy="Lett", medium="Middels", hard="Vanskelig", expert="Ekspert"),
  f_align="Plassering", f_align_center="Midtstilt", f_align_left="Venstre",
  f_kind="Type", f_kind_script="Med skript (anbefalt)", f_kind_iframe="Bare iframe",
  f_page="Bakgrunn i forhåndsvisningen", f_page_light="Lys avisside", f_page_dark="Mørk avisside",
  code="Kode", html_label="HTML", html_noscript="HTML uten skript",
  options="Valg", options_lead="Valgene settes som attributter på <code>&lt;div data-hiku&gt;</code>.",
  th_attr="Attributt", th_values="Verdier", th_what="Hva det gjør",
  opt_lang="Språket i spillet: norsk, engelsk, svensk, dansk, finsk eller tysk. Uten dette brukes språket på siden rundt (<code>&lt;html lang=\"…\"&gt;</code>), og ellers norsk.",
  opt_theme="Låser fargene. Uten dette følger spillet leserens lyse eller mørke modus.",
  opt_align="Plasserer spillet til venstre. Uten dette står det midt i plassen det får, og er aldri bredere enn 480 piksler.",
  opt_level="Hvilket av dagens fire brett som vises først. Uten dette åpner spillet på nivået leseren spilte sist, og ellers på Lett. Leseren kan alltid bytte.",
  example="Eksempel, alltid lyst og med Middels først:",
  noscript="Uten skript",
  noscript_lead="Tillater ikke publiseringssystemet skript, kan spillet legges inn som en vanlig <code>iframe</code>. Da tilpasser ikke høyden seg selv, så sett den fast. 860 piksler gir plass til hele spillet, også når et brett er løst; spillet er aldri bredere enn 480 piksler.",
  noscript_after="Valgene settes da i adressen: <code>?lang=sv</code>, <code>&amp;theme=dark</code>, <code>&amp;level=hard</code>. Plasseringen styres av stilen på rammen; fjern <code>margin:0 auto</code> for å legge den til venstre.",
  privacy="Personvern og drift",
  p_cookies="<strong>Ingen informasjonskapsler og ingen sporing.</strong> Ingen spilldata eller resultater sendes til oss. Resultater og stjerner lagres bare i leserens egen nettleser. Lenken til App Store inneholder navnet på nettstedet spillet står på, slik at vi i App Store Connect kan se samlet hvor mange som kom fra hver side. Den informasjonen går bare til Apple, og bare hvis leseren trykker på lenken. Vertstjenesten mottar vanlige tekniske forespørsler når filene lastes, som for alle nettsider.",
  p_isolated="<strong>Isolert spill.</strong> Selve spillet kjører i en <code>iframe</code> fra en annen adresse og kan ikke lese eller påvirke siden rundt seg. Det lille innlastingsskriptet, <code>embed.js</code>, kjører på avisens side som andre eksterne skript: det oppretter rammen og tilpasser høyden, og gjør ikke noe annet. Kildekoden er kort og kan leses på <a href=\"embed.js\">embed.js</a>. Redaksjoner som ikke tillater eksterne skript, bruker iframe-versjonen.",
  p_light="<strong>Lett.</strong> Første gang lastes rundt 70 kB komprimert. Rammen lastes først når leseren nærmer seg den.",
  p_midnight="<strong>Nye brett ved midnatt</strong> i leserens tidssone. Biblioteket rekker i tre år, og brettene er de samme som i appen.",
  p_host="<strong>Driftes på {host}.</strong> Vertstjenesten ser leserens IP-adresse når filene lastes, som for alle nettsider.",
  tech="For tekniske redaksjoner",
  strict="Anbefalt for strenge sikkerhetskrav",
  strict_text="Bruk iframe-versjonen over. Da kjører ingen kode fra oss på deres side, bare i rammen. Det eneste dere mister, er at høyden ikke tilpasser seg selv.",
  csp_lead="Med innlastingsskriptet trengs begge disse; med ren iframe bare den siste:",
  csp_after="Legg dem til i de eksisterende direktivene deres. Spillet i rammen henter bare filer fra samme adresse.",
  stability="Stabilitet",
  s1="Adressene <code>…/daily/embed.js</code> og <code>…/daily/</code>, og attributtene i tabellen over, blir stående. Nye valg legges til uten å endre de eksisterende.",
  s2="Skriptet lastes med <code>async</code> og holder aldri igjen resten av siden.",
  s3="Er {host} utilgjengelig, blir plassen der spillet skulle stått tom. Siden rundt påvirkes ikke.",
  terms="Vilkår",
  terms_text="<strong>Dagens Hiku er gratis å bruke</strong>, på nettaviser, blogger og andre nettsider. Det eneste kravet er at lenken til Hiku-appen i spillet står som den er: ikke skjul, fjern eller dekk den til.",
  contact="Kontakt",
  contact_text="Har du spørsmål, eller vil du vite mer før dere tar det i bruk? Send en e-post til <a href=\"mailto:es@rubberduck.no\">es@rubberduck.no</a>.",
  play="Spill Dagens Hiku", about="Om Hiku",
  copy="Kopier", copied="Kopiert!", copied_sr="Koden er kopiert.", copy_failed="Merk og kopier", copy_failed_sr="Kunne ikke kopiere. Merk koden og kopier den selv.",
  language="Språk",
),
"en": dict(
  title="Daily Hiku on your site",
  description="How to embed Daily Hiku, a daily number puzzle, on a news site or any web page: two lines of code, no cookies.",
  lead="Daily Hiku is a calm number puzzle with four new boards every day, from easy to expert. It is free to embed on a news site or any web page, with two lines of code.",
  rule="The rule is short: the number says how far it jumps, across or up and down. When it lands on another number, the smaller is taken from the larger. The goal is to make every number disappear. The boards are the same as in the Hiku app for iPhone.",
  how="How to do it",
  step1="Paste the code below where the game should appear, for example in an article or on a puzzle page of its own.",
  step2="Publish. The game fetches today's boards itself and adjusts its height.",
  once="The script only needs to appear once per page, even with several games on the same page.",
  try_="Try and copy",
  try_lead="Pick the settings, watch the game change, and copy the code when you are happy with it.",
  f_lang="Language", f_lang_page="The page's own language",
  lang_names=dict(nb="Norwegian", en="English", sv="Swedish", da="Danish", fi="Finnish", de="German"),
  f_theme="Colours", f_theme_auto="Follow the reader", f_theme_light="Always light", f_theme_dark="Always dark",
  f_level="First board", f_level_last="The reader's last level",
  levels=dict(easy="Easy", medium="Medium", hard="Hard", expert="Expert"),
  f_align="Position", f_align_center="Centred", f_align_left="Left",
  f_kind="Type", f_kind_script="With script (recommended)", f_kind_iframe="Iframe only",
  f_page="Preview background", f_page_light="Light news page", f_page_dark="Dark news page",
  code="Code", html_label="HTML", html_noscript="HTML without script",
  options="Options", options_lead="Options are set as attributes on <code>&lt;div data-hiku&gt;</code>.",
  th_attr="Attribute", th_values="Values", th_what="What it does",
  opt_lang="The game's language: Norwegian, English, Swedish, Danish, Finnish or German. Without it, the language of the surrounding page (<code>&lt;html lang=\"…\"&gt;</code>) is used, and otherwise Norwegian.",
  opt_theme="Fixes the colours. Without it, the game follows the reader's light or dark mode.",
  opt_align="Puts the game at the left. Without it, the game is centred in the space it is given, and is never wider than 480 pixels.",
  opt_level="Which of today's four boards is shown first. Without it, the game opens on the level the reader played last, and otherwise on Easy. The reader can always switch.",
  example="Example, always light and with Medium first:",
  noscript="Without script",
  noscript_lead="If your publishing system does not allow scripts, embed the game as a plain <code>iframe</code>. Its height then does not adjust itself, so set it. 860 pixels fits the whole game, including a solved board; the game is never wider than 480 pixels.",
  noscript_after="Options then go in the address: <code>?lang=sv</code>, <code>&amp;theme=dark</code>, <code>&amp;level=hard</code>. The position is set by the frame's style; remove <code>margin:0 auto</code> to put it at the left.",
  privacy="Privacy and operation",
  p_cookies="<strong>No cookies and no tracking.</strong> No game data or results are sent to us. Results and stars are stored only in the reader's own browser. The App Store link carries the name of the site the game is on, so we can see in App Store Connect how many came from each site in total. Only Apple receives it, and only if the reader follows the link. The host receives ordinary technical requests when the files load, as with any web page.",
  p_isolated="<strong>An isolated game.</strong> The game itself runs in an <code>iframe</code> from another address and cannot read or affect the page around it. The small loader script, <code>embed.js</code>, runs on your page like any other external script: it creates the frame and sets its height, and does nothing else. Its source is short and can be read at <a href=\"embed.js\">embed.js</a>. Newsrooms that do not allow external scripts use the iframe version.",
  p_light="<strong>Light.</strong> The first load is about 70 kB compressed. The frame only loads as the reader approaches it.",
  p_midnight="<strong>New boards at midnight</strong> in the reader's time zone. The library lasts three years, and the boards are the same as in the app.",
  p_host="<strong>Hosted on {host}.</strong> The host sees the reader's IP address when the files load, as with any web page.",
  tech="For technical teams",
  strict="Recommended for strict security requirements",
  strict_text="Use the iframe version above. Then no code of ours runs on your page, only inside the frame. All you lose is the automatic height.",
  csp_lead="With the loader script both are needed; with a plain iframe only the second:",
  csp_after="Add them to your existing directives. The game in the frame only loads files from the same address.",
  stability="Stability",
  s1="The addresses <code>…/daily/embed.js</code> and <code>…/daily/</code>, and the attributes in the table above, will stay. New options are added without changing existing ones.",
  s2="The script loads with <code>async</code> and never holds up the rest of the page.",
  s3="If {host} is unavailable, the space where the game would be stays empty. The page around it is not affected.",
  terms="Terms",
  terms_text="<strong>Daily Hiku is free to use</strong> on news sites, blogs and any other web pages. The only requirement is that the link to the Hiku app inside the game stays as it is: do not hide, remove or cover it.",
  contact="Contact",
  contact_text="Questions, or want to know more before you start? Email <a href=\"mailto:es@rubberduck.no\">es@rubberduck.no</a>.",
  play="Play Daily Hiku", about="About Hiku",
  copy="Copy", copied="Copied!", copied_sr="The code is copied.", copy_failed="Select and copy", copy_failed_sr="Could not copy. Select the code and copy it yourself.",
  language="Language",
),
"sv": dict(
  title="Dagens Hiku på din webbplats",
  description="Så bäddar du in Dagens Hiku, ett dagligt sifferspel, på en nyhetssajt eller webbplats: två rader kod, inga kakor.",
  lead="Dagens Hiku är ett lugnt sifferspel med fyra nya bräden varje dag, från lätt till expert. Det är gratis att bädda in på en nyhetssajt eller webbplats, med två rader kod.",
  rule="Regeln är kort: talet säger hur långt det hoppar, vågrätt eller lodrätt. Landar det på ett annat tal dras det mindre från det större. Målet är att få alla tal att försvinna. Bräden är desamma som i Hiku-appen för iPhone.",
  how="Så gör du",
  step1="Klistra in koden nedan där spelet ska synas, till exempel i en artikel eller på en egen spelsida.",
  step2="Publicera. Spelet hämtar dagens bräden själv och anpassar sin höjd.",
  once="Skriptet behöver bara finnas en gång per sida, även om sidan har flera spel.",
  try_="Prova och kopiera",
  try_lead="Välj inställningar, se spelet ändras och kopiera koden när ni är nöjda.",
  f_lang="Språk", f_lang_page="Sidans eget språk",
  lang_names=dict(nb="Norska", en="Engelska", sv="Svenska", da="Danska", fi="Finska", de="Tyska"),
  f_theme="Färger", f_theme_auto="Följ läsaren", f_theme_light="Alltid ljust", f_theme_dark="Alltid mörkt",
  f_level="Första brädet", f_level_last="Läsarens senaste nivå",
  levels=dict(easy="Lätt", medium="Medel", hard="Svår", expert="Expert"),
  f_align="Placering", f_align_center="Centrerat", f_align_left="Vänster",
  f_kind="Typ", f_kind_script="Med skript (rekommenderas)", f_kind_iframe="Endast iframe",
  f_page="Bakgrund i förhandsvisningen", f_page_light="Ljus nyhetssida", f_page_dark="Mörk nyhetssida",
  code="Kod", html_label="HTML", html_noscript="HTML utan skript",
  options="Inställningar", options_lead="Inställningarna anges som attribut på <code>&lt;div data-hiku&gt;</code>.",
  th_attr="Attribut", th_values="Värden", th_what="Vad det gör",
  opt_lang="Spelets språk: norska, engelska, svenska, danska, finska eller tyska. Utan detta används sidans eget språk (<code>&lt;html lang=\"…\"&gt;</code>), annars norska.",
  opt_theme="Låser färgerna. Utan detta följer spelet läsarens ljusa eller mörka läge.",
  opt_align="Placerar spelet till vänster. Utan detta står det centrerat i det utrymme det får och är aldrig bredare än 480 pixlar.",
  opt_level="Vilket av dagens fyra bräden som visas först. Utan detta öppnar spelet på den nivå läsaren spelade senast, annars på Lätt. Läsaren kan alltid byta.",
  example="Exempel, alltid ljust och med Medel först:",
  noscript="Utan skript",
  noscript_lead="Tillåter inte publiceringssystemet skript kan spelet läggas in som en vanlig <code>iframe</code>. Då anpassar sig inte höjden själv, så ange den. 860 pixlar räcker för hela spelet, även när ett bräde är löst; spelet är aldrig bredare än 480 pixlar.",
  noscript_after="Inställningarna anges då i adressen: <code>?lang=sv</code>, <code>&amp;theme=dark</code>, <code>&amp;level=hard</code>. Placeringen styrs av ramens stil; ta bort <code>margin:0 auto</code> för att lägga den till vänster.",
  privacy="Integritet och drift",
  p_cookies="<strong>Inga kakor och ingen spårning.</strong> Inga speldata eller resultat skickas till oss. Resultat och stjärnor sparas bara i läsarens egen webbläsare. Länken till App Store innehåller namnet på webbplatsen spelet finns på, så att vi i App Store Connect kan se hur många som kom från varje sida totalt. Bara Apple får den uppgiften, och bara om läsaren trycker på länken. Värdtjänsten tar emot vanliga tekniska förfrågningar när filerna laddas, som för alla webbsidor.",
  p_isolated="<strong>Isolerat spel.</strong> Själva spelet körs i en <code>iframe</code> från en annan adress och kan inte läsa eller påverka sidan runt omkring. Det lilla laddningsskriptet, <code>embed.js</code>, körs på er sida som andra externa skript: det skapar ramen och anpassar höjden, och gör inget annat. Källkoden är kort och kan läsas på <a href=\"embed.js\">embed.js</a>. Redaktioner som inte tillåter externa skript använder iframe-versionen.",
  p_light="<strong>Lätt.</strong> Första gången laddas cirka 70 kB komprimerat. Ramen laddas först när läsaren närmar sig den.",
  p_midnight="<strong>Nya bräden vid midnatt</strong> i läsarens tidszon. Biblioteket räcker i tre år, och bräden är desamma som i appen.",
  p_host="<strong>Driftas på {host}.</strong> Värdtjänsten ser läsarens IP-adress när filerna laddas, som för alla webbsidor.",
  tech="För tekniska redaktioner",
  strict="Rekommenderas vid höga säkerhetskrav",
  strict_text="Använd iframe-versionen ovan. Då körs ingen kod från oss på er sida, bara i ramen. Det enda ni förlorar är att höjden inte anpassar sig själv.",
  csp_lead="Med laddningsskriptet behövs båda; med ren iframe bara den sista:",
  csp_after="Lägg till dem i era befintliga direktiv. Spelet i ramen hämtar bara filer från samma adress.",
  stability="Stabilitet",
  s1="Adresserna <code>…/daily/embed.js</code> och <code>…/daily/</code>, och attributen i tabellen ovan, ligger kvar. Nya inställningar läggs till utan att ändra de befintliga.",
  s2="Skriptet laddas med <code>async</code> och håller aldrig upp resten av sidan.",
  s3="Är {host} otillgängligt blir platsen där spelet skulle stå tom. Sidan runt omkring påverkas inte.",
  terms="Villkor",
  terms_text="<strong>Dagens Hiku är gratis att använda</strong> på nyhetssajter, bloggar och andra webbplatser. Det enda kravet är att länken till Hiku-appen i spelet står kvar som den är: dölj, ta bort eller täck inte över den.",
  contact="Kontakt",
  contact_text="Har du frågor eller vill veta mer innan ni börjar? Skicka e-post till <a href=\"mailto:es@rubberduck.no\">es@rubberduck.no</a>.",
  play="Spela Dagens Hiku", about="Om Hiku",
  copy="Kopiera", copied="Kopierat!", copied_sr="Koden är kopierad.", copy_failed="Markera och kopiera", copy_failed_sr="Kunde inte kopiera. Markera koden och kopiera den själv.",
  language="Språk",
),
"da": dict(
  title="Dagens Hiku på dit website",
  description="Sådan indlejrer du Dagens Hiku, et dagligt talspil, på et netmedie eller website: to linjer kode, ingen cookies.",
  lead="Dagens Hiku er et roligt talspil med fire nye brætter hver dag, fra let til ekspert. Det er gratis at indlejre på et netmedie eller website, med to linjer kode.",
  rule="Reglen er kort: tallet siger, hvor langt det springer, vandret eller lodret. Lander det på et andet tal, trækkes det mindste fra det største. Målet er at få alle tallene til at forsvinde. Brætterne er de samme som i Hiku-appen til iPhone.",
  how="Sådan gør du",
  step1="Indsæt koden nedenfor, hvor spillet skal stå, for eksempel i en artikel eller på en selvstændig spilside.",
  step2="Udgiv. Spillet henter selv dagens brætter og tilpasser sin højde.",
  once="Scriptet skal kun stå én gang pr. side, også selvom siden har flere spil.",
  try_="Prøv og kopiér",
  try_lead="Vælg indstillingerne, se spillet ændre sig, og kopiér koden, når I er tilfredse.",
  f_lang="Sprog", f_lang_page="Sidens eget sprog",
  lang_names=dict(nb="Norsk", en="Engelsk", sv="Svensk", da="Dansk", fi="Finsk", de="Tysk"),
  f_theme="Farver", f_theme_auto="Følg læseren", f_theme_light="Altid lyst", f_theme_dark="Altid mørkt",
  f_level="Første bræt", f_level_last="Læserens seneste niveau",
  levels=dict(easy="Let", medium="Middel", hard="Svær", expert="Ekspert"),
  f_align="Placering", f_align_center="Centreret", f_align_left="Venstre",
  f_kind="Type", f_kind_script="Med script (anbefalet)", f_kind_iframe="Kun iframe",
  f_page="Baggrund i forhåndsvisningen", f_page_light="Lys nyhedsside", f_page_dark="Mørk nyhedsside",
  code="Kode", html_label="HTML", html_noscript="HTML uden script",
  options="Indstillinger", options_lead="Indstillingerne angives som attributter på <code>&lt;div data-hiku&gt;</code>.",
  th_attr="Attribut", th_values="Værdier", th_what="Hvad det gør",
  opt_lang="Spillets sprog: norsk, engelsk, svensk, dansk, finsk eller tysk. Uden dette bruges sidens eget sprog (<code>&lt;html lang=\"…\"&gt;</code>), ellers norsk.",
  opt_theme="Låser farverne. Uden dette følger spillet læserens lyse eller mørke tilstand.",
  opt_align="Placerer spillet til venstre. Uden dette står det centreret i den plads, det får, og er aldrig bredere end 480 pixel.",
  opt_level="Hvilket af dagens fire brætter der vises først. Uden dette åbner spillet på det niveau, læseren spillede sidst, ellers på Let. Læseren kan altid skifte.",
  example="Eksempel, altid lyst og med Middel først:",
  noscript="Uden script",
  noscript_lead="Tillader jeres publiceringssystem ikke scripts, kan spillet indsættes som en almindelig <code>iframe</code>. Så tilpasser højden sig ikke selv, så angiv den. 860 pixel giver plads til hele spillet, også når et bræt er løst; spillet er aldrig bredere end 480 pixel.",
  noscript_after="Indstillingerne angives så i adressen: <code>?lang=sv</code>, <code>&amp;theme=dark</code>, <code>&amp;level=hard</code>. Placeringen styres af rammens stil; fjern <code>margin:0 auto</code> for at placere den til venstre.",
  privacy="Privatliv og drift",
  p_cookies="<strong>Ingen cookies og ingen sporing.</strong> Ingen spildata eller resultater sendes til os. Resultater og stjerner gemmes kun i læserens egen browser. Linket til App Store indeholder navnet på det website, spillet står på, så vi i App Store Connect kan se, hvor mange der samlet kom fra hver side. Kun Apple får den oplysning, og kun hvis læseren trykker på linket. Værtstjenesten modtager almindelige tekniske forespørgsler, når filerne indlæses, som for alle websider.",
  p_isolated="<strong>Isoleret spil.</strong> Selve spillet kører i en <code>iframe</code> fra en anden adresse og kan ikke læse eller påvirke siden omkring sig. Det lille indlæsningsscript, <code>embed.js</code>, kører på jeres side som andre eksterne scripts: det opretter rammen og tilpasser højden og gør ikke andet. Kildekoden er kort og kan læses på <a href=\"embed.js\">embed.js</a>. Redaktioner, der ikke tillader eksterne scripts, bruger iframe-versionen.",
  p_light="<strong>Let.</strong> Første gang indlæses omkring 70 kB komprimeret. Rammen indlæses først, når læseren nærmer sig den.",
  p_midnight="<strong>Nye brætter ved midnat</strong> i læserens tidszone. Biblioteket rækker i tre år, og brætterne er de samme som i appen.",
  p_host="<strong>Drives på {host}.</strong> Værtstjenesten ser læserens IP-adresse, når filerne indlæses, som for alle websider.",
  tech="Til tekniske redaktioner",
  strict="Anbefalet ved strenge sikkerhedskrav",
  strict_text="Brug iframe-versionen ovenfor. Så kører ingen kode fra os på jeres side, kun i rammen. Det eneste, I mister, er at højden ikke tilpasser sig selv.",
  csp_lead="Med indlæsningsscriptet kræves begge; med ren iframe kun den sidste:",
  csp_after="Tilføj dem til jeres eksisterende direktiver. Spillet i rammen henter kun filer fra samme adresse.",
  stability="Stabilitet",
  s1="Adresserne <code>…/daily/embed.js</code> og <code>…/daily/</code>, og attributterne i tabellen ovenfor, bliver stående. Nye indstillinger tilføjes uden at ændre de eksisterende.",
  s2="Scriptet indlæses med <code>async</code> og holder aldrig resten af siden tilbage.",
  s3="Er {host} utilgængelig, bliver pladsen, hvor spillet skulle stå, tom. Siden omkring påvirkes ikke.",
  terms="Vilkår",
  terms_text="<strong>Dagens Hiku er gratis at bruge</strong> på netmedier, blogs og andre websites. Det eneste krav er, at linket til Hiku-appen i spillet står, som det er: skjul, fjern eller dæk det ikke til.",
  contact="Kontakt",
  contact_text="Har du spørgsmål, eller vil du vide mere, før I går i gang? Skriv til <a href=\"mailto:es@rubberduck.no\">es@rubberduck.no</a>.",
  play="Spil Dagens Hiku", about="Om Hiku",
  copy="Kopiér", copied="Kopieret!", copied_sr="Koden er kopieret.", copy_failed="Markér og kopiér", copy_failed_sr="Kunne ikke kopiere. Markér koden, og kopiér den selv.",
  language="Sprog",
),
"fi": dict(
  title="Päivän Hiku sivustollesi",
  description="Näin upotat Päivän Hikun, päivittäisen numeropelin, uutissivustolle tai verkkosivulle: kaksi riviä koodia, ei evästeitä.",
  lead="Päivän Hiku on rauhallinen numeropeli, jossa on neljä uutta lautaa joka päivä helposta asiantuntijaan. Sen voi upottaa maksutta uutissivustolle tai verkkosivulle kahdella rivillä koodia.",
  rule="Sääntö on lyhyt: luku kertoo, kuinka pitkälle se hyppää vaaka- tai pystysuunnassa. Kun se laskeutuu toiseen lukuun, pienempi vähennetään suuremmasta. Tavoitteena on saada kaikki luvut katoamaan. Laudat ovat samat kuin iPhonen Hiku-sovelluksessa.",
  how="Näin teet sen",
  step1="Liitä alla oleva koodi kohtaan, jossa pelin pitää näkyä, esimerkiksi artikkeliin tai omalle pelisivulle.",
  step2="Julkaise. Peli hakee päivän laudat itse ja säätää korkeutensa.",
  once="Skriptin tarvitsee olla sivulla vain kerran, vaikka sivulla olisi useita pelejä.",
  try_="Kokeile ja kopioi",
  try_lead="Valitse asetukset, katso miten peli muuttuu, ja kopioi koodi, kun olet tyytyväinen.",
  f_lang="Kieli", f_lang_page="Sivun oma kieli",
  lang_names=dict(nb="Norja", en="Englanti", sv="Ruotsi", da="Tanska", fi="Suomi", de="Saksa"),
  f_theme="Värit", f_theme_auto="Lukijan mukaan", f_theme_light="Aina vaalea", f_theme_dark="Aina tumma",
  f_level="Ensimmäinen lauta", f_level_last="Lukijan edellinen taso",
  levels=dict(easy="Helppo", medium="Keskitaso", hard="Vaikea", expert="Asiantuntija"),
  f_align="Sijainti", f_align_center="Keskellä", f_align_left="Vasemmalla",
  f_kind="Tyyppi", f_kind_script="Skriptillä (suositus)", f_kind_iframe="Pelkkä iframe",
  f_page="Esikatselun tausta", f_page_light="Vaalea uutissivu", f_page_dark="Tumma uutissivu",
  code="Koodi", html_label="HTML", html_noscript="HTML ilman skriptiä",
  options="Asetukset", options_lead="Asetukset annetaan <code>&lt;div data-hiku&gt;</code>-elementin attribuutteina.",
  th_attr="Attribuutti", th_values="Arvot", th_what="Mitä se tekee",
  opt_lang="Pelin kieli: norja, englanti, ruotsi, tanska, suomi tai saksa. Ilman tätä käytetään ympäröivän sivun kieltä (<code>&lt;html lang=\"…\"&gt;</code>), muuten norjaa.",
  opt_theme="Lukitsee värit. Ilman tätä peli seuraa lukijan vaaleaa tai tummaa tilaa.",
  opt_align="Sijoittaa pelin vasemmalle. Ilman tätä peli on keskellä sille annettua tilaa eikä ole koskaan yli 480 pikseliä leveä.",
  opt_level="Mikä päivän neljästä laudasta näytetään ensin. Ilman tätä peli aukeaa tasolla, jota lukija pelasi viimeksi, muuten Helppo-tasolla. Lukija voi aina vaihtaa.",
  example="Esimerkki, aina vaalea ja Keskitaso ensin:",
  noscript="Ilman skriptiä",
  noscript_lead="Jos julkaisujärjestelmä ei salli skriptejä, pelin voi upottaa tavallisena <code>iframe</code>-kehyksenä. Silloin korkeus ei säädy itsestään, joten aseta se. 860 pikseliä riittää koko peliin myös ratkaistun laudan kanssa; peli ei ole koskaan yli 480 pikseliä leveä.",
  noscript_after="Asetukset annetaan silloin osoitteessa: <code>?lang=sv</code>, <code>&amp;theme=dark</code>, <code>&amp;level=hard</code>. Sijainti määräytyy kehyksen tyylistä; poista <code>margin:0 auto</code>, niin kehys on vasemmalla.",
  privacy="Tietosuoja ja ylläpito",
  p_cookies="<strong>Ei evästeitä eikä seurantaa.</strong> Meille ei lähetetä pelitietoja eikä tuloksia. Tulokset ja tähdet tallentuvat vain lukijan omaan selaimeen. App Store -linkki sisältää sen sivuston nimen, jolla peli on, jotta näemme App Store Connectissa, kuinka moni tuli kultakin sivulta yhteensä. Tieto menee vain Applelle ja vain, jos lukija avaa linkin. Palvelin vastaanottaa tavallisia teknisiä pyyntöjä, kun tiedostot latautuvat, kuten kaikilla verkkosivuilla.",
  p_isolated="<strong>Eristetty peli.</strong> Itse peli toimii <code>iframe</code>-kehyksessä toisesta osoitteesta eikä voi lukea tai muuttaa ympäröivää sivua. Pieni latausskripti, <code>embed.js</code>, toimii sivullanne kuten muutkin ulkoiset skriptit: se luo kehyksen ja säätää sen korkeuden eikä tee muuta. Sen lähdekoodi on lyhyt ja luettavissa osoitteessa <a href=\"embed.js\">embed.js</a>. Toimitukset, jotka eivät salli ulkoisia skriptejä, käyttävät iframe-versiota.",
  p_light="<strong>Kevyt.</strong> Ensimmäisellä kerralla ladataan noin 70 kt pakattuna. Kehys latautuu vasta, kun lukija lähestyy sitä.",
  p_midnight="<strong>Uudet laudat keskiyöllä</strong> lukijan aikavyöhykkeellä. Kirjasto riittää kolmeksi vuodeksi, ja laudat ovat samat kuin sovelluksessa.",
  p_host="<strong>Ylläpitopalvelu on {host}.</strong> Palvelin näkee lukijan IP-osoitteen, kun tiedostot latautuvat, kuten kaikilla verkkosivuilla.",
  tech="Teknisille toimituksille",
  strict="Suositus tiukkoihin tietoturvavaatimuksiin",
  strict_text="Käytä yllä olevaa iframe-versiota. Silloin sivullanne ei suoriteta meidän koodiamme, vain kehyksessä. Menetätte ainoastaan automaattisen korkeuden.",
  csp_lead="Latausskriptin kanssa tarvitaan molemmat; pelkän iframen kanssa vain jälkimmäinen:",
  csp_after="Lisää ne nykyisiin direktiiveihinne. Kehyksessä oleva peli lataa tiedostoja vain samasta osoitteesta.",
  stability="Vakaus",
  s1="Osoitteet <code>…/daily/embed.js</code> ja <code>…/daily/</code> sekä yllä olevan taulukon attribuutit pysyvät. Uusia asetuksia lisätään muuttamatta nykyisiä.",
  s2="Skripti ladataan <code>async</code>-määreellä eikä koskaan hidasta muuta sivua.",
  s3="Jos {host} ei ole käytettävissä, pelin paikka jää tyhjäksi. Ympäröivä sivu ei kärsi.",
  terms="Ehdot",
  terms_text="<strong>Päivän Hiku on maksuton</strong> uutissivustoilla, blogeissa ja muilla verkkosivuilla. Ainoa vaatimus on, että pelin linkki Hiku-sovellukseen pysyy ennallaan: älä piilota, poista tai peitä sitä.",
  contact="Yhteystiedot",
  contact_text="Kysyttävää, tai haluatko tietää lisää ennen käyttöönottoa? Lähetä sähköpostia osoitteeseen <a href=\"mailto:es@rubberduck.no\">es@rubberduck.no</a>.",
  play="Pelaa Päivän Hikua", about="Tietoa Hikusta",
  copy="Kopioi", copied="Kopioitu!", copied_sr="Koodi on kopioitu.", copy_failed="Valitse ja kopioi", copy_failed_sr="Kopiointi ei onnistunut. Valitse koodi ja kopioi se itse.",
  language="Kieli",
),
"de": dict(
  title="Hiku des Tages auf Ihrer Website",
  description="So binden Sie Hiku des Tages, ein tägliches Zahlenrätsel, in eine Nachrichtenseite oder Website ein: zwei Zeilen Code, keine Cookies.",
  lead="Hiku des Tages ist ein ruhiges Zahlenrätsel mit vier neuen Brettern jeden Tag, von leicht bis Experte. Es lässt sich kostenlos in eine Nachrichtenseite oder Website einbinden, mit zwei Zeilen Code.",
  rule="Die Regel ist kurz: Die Zahl sagt, wie weit sie springt, waagerecht oder senkrecht. Landet sie auf einer anderen Zahl, wird die kleinere von der größeren abgezogen. Ziel ist, alle Zahlen verschwinden zu lassen. Die Bretter sind dieselben wie in der Hiku-App für iPhone.",
  how="So geht es",
  step1="Fügen Sie den Code unten dort ein, wo das Spiel erscheinen soll, zum Beispiel in einem Artikel oder auf einer eigenen Rätselseite.",
  step2="Veröffentlichen. Das Spiel lädt die Bretter des Tages selbst und passt seine Höhe an.",
  once="Das Skript muss nur einmal pro Seite stehen, auch wenn die Seite mehrere Spiele enthält.",
  try_="Ausprobieren und kopieren",
  try_lead="Wählen Sie die Einstellungen, sehen Sie, wie sich das Spiel ändert, und kopieren Sie den Code, wenn alles passt.",
  f_lang="Sprache", f_lang_page="Sprache der Seite",
  lang_names=dict(nb="Norwegisch", en="Englisch", sv="Schwedisch", da="Dänisch", fi="Finnisch", de="Deutsch"),
  f_theme="Farben", f_theme_auto="Wie beim Leser", f_theme_light="Immer hell", f_theme_dark="Immer dunkel",
  f_level="Erstes Brett", f_level_last="Letztes Level des Lesers",
  levels=dict(easy="Leicht", medium="Mittel", hard="Schwer", expert="Experte"),
  f_align="Ausrichtung", f_align_center="Zentriert", f_align_left="Links",
  f_kind="Art", f_kind_script="Mit Skript (empfohlen)", f_kind_iframe="Nur iframe",
  f_page="Hintergrund der Vorschau", f_page_light="Helle Nachrichtenseite", f_page_dark="Dunkle Nachrichtenseite",
  code="Code", html_label="HTML", html_noscript="HTML ohne Skript",
  options="Optionen", options_lead="Die Optionen werden als Attribute am <code>&lt;div data-hiku&gt;</code> gesetzt.",
  th_attr="Attribut", th_values="Werte", th_what="Wirkung",
  opt_lang="Sprache des Spiels: Norwegisch, Englisch, Schwedisch, Dänisch, Finnisch oder Deutsch. Ohne diese Angabe gilt die Sprache der umgebenden Seite (<code>&lt;html lang=\"…\"&gt;</code>), sonst Norwegisch.",
  opt_theme="Legt die Farben fest. Ohne diese Angabe folgt das Spiel dem hellen oder dunklen Modus des Lesers.",
  opt_align="Setzt das Spiel nach links. Ohne diese Angabe steht es zentriert im verfügbaren Platz und ist nie breiter als 480 Pixel.",
  opt_level="Welches der vier Bretter des Tages zuerst erscheint. Ohne diese Angabe öffnet das Spiel mit dem Level, das der Leser zuletzt gespielt hat, sonst mit Leicht. Der Leser kann jederzeit wechseln.",
  example="Beispiel, immer hell und mit Mittel zuerst:",
  noscript="Ohne Skript",
  noscript_lead="Erlaubt Ihr Redaktionssystem keine Skripte, binden Sie das Spiel als einfaches <code>iframe</code> ein. Die Höhe passt sich dann nicht selbst an, also legen Sie sie fest. 860 Pixel reichen für das ganze Spiel, auch mit gelöstem Brett; das Spiel ist nie breiter als 480 Pixel.",
  noscript_after="Die Optionen stehen dann in der Adresse: <code>?lang=sv</code>, <code>&amp;theme=dark</code>, <code>&amp;level=hard</code>. Die Ausrichtung ergibt sich aus dem Stil des Rahmens; entfernen Sie <code>margin:0 auto</code>, um ihn links auszurichten.",
  privacy="Datenschutz und Betrieb",
  p_cookies="<strong>Keine Cookies und kein Tracking.</strong> Es werden keine Spieldaten oder Ergebnisse an uns gesendet. Ergebnisse und Sterne werden nur im Browser des Lesers gespeichert. Der Link zum App Store enthält den Namen der Website, auf der das Spiel steht, damit wir in App Store Connect sehen, wie viele insgesamt von jeder Seite kamen. Diese Angabe erhält nur Apple, und nur wenn der Leser dem Link folgt. Der Hoster erhält beim Laden der Dateien übliche technische Anfragen, wie bei jeder Website.",
  p_isolated="<strong>Isoliertes Spiel.</strong> Das Spiel selbst läuft in einem <code>iframe</code> von einer anderen Adresse und kann die umgebende Seite weder lesen noch beeinflussen. Das kleine Ladeskript <code>embed.js</code> läuft auf Ihrer Seite wie andere externe Skripte: Es erstellt den Rahmen und passt die Höhe an, sonst nichts. Der Quelltext ist kurz und unter <a href=\"embed.js\">embed.js</a> einsehbar. Redaktionen, die keine externen Skripte erlauben, nutzen die iframe-Variante.",
  p_light="<strong>Leicht.</strong> Beim ersten Mal werden etwa 70 kB komprimiert geladen. Der Rahmen lädt erst, wenn der Leser sich ihm nähert.",
  p_midnight="<strong>Neue Bretter um Mitternacht</strong> in der Zeitzone des Lesers. Die Bibliothek reicht für drei Jahre, und die Bretter sind dieselben wie in der App.",
  p_host="<strong>Gehostet bei {host}.</strong> Der Hoster sieht beim Laden der Dateien die IP-Adresse des Lesers, wie bei jeder Website.",
  tech="Für technische Teams",
  strict="Empfohlen bei strengen Sicherheitsanforderungen",
  strict_text="Nutzen Sie die iframe-Variante oben. Dann läuft kein Code von uns auf Ihrer Seite, nur im Rahmen. Sie verzichten lediglich auf die automatische Höhe.",
  csp_lead="Mit dem Ladeskript werden beide benötigt, mit reinem iframe nur die zweite:",
  csp_after="Ergänzen Sie Ihre bestehenden Direktiven. Das Spiel im Rahmen lädt nur Dateien von derselben Adresse.",
  stability="Stabilität",
  s1="Die Adressen <code>…/daily/embed.js</code> und <code>…/daily/</code> sowie die Attribute in der Tabelle oben bleiben bestehen. Neue Optionen kommen hinzu, ohne bestehende zu ändern.",
  s2="Das Skript lädt mit <code>async</code> und hält den Rest der Seite nie auf.",
  s3="Ist {host} nicht erreichbar, bleibt der Platz für das Spiel leer. Die umgebende Seite ist nicht betroffen.",
  terms="Bedingungen",
  terms_text="<strong>Hiku des Tages ist kostenlos nutzbar</strong> auf Nachrichtenseiten, Blogs und anderen Websites. Einzige Bedingung: Der Link zur Hiku-App im Spiel bleibt, wie er ist. Bitte nicht ausblenden, entfernen oder überdecken.",
  contact="Kontakt",
  contact_text="Fragen, oder möchten Sie vor dem Einsatz mehr wissen? Schreiben Sie an <a href=\"mailto:es@rubberduck.no\">es@rubberduck.no</a>.",
  play="Hiku des Tages spielen", about="Über Hiku",
  copy="Kopieren", copied="Kopiert!", copied_sr="Der Code ist kopiert.", copy_failed="Markieren und kopieren", copy_failed_sr="Kopieren nicht möglich. Bitte den Code markieren und selbst kopieren.",
  language="Sprache",
),
}

TEMPLATE = pathlib.Path(__file__).with_name("guide_template.html").read_text(encoding="utf-8")


def build(lang):
    t = T[lang]
    e = html.escape
    host_code = f'&lt;script src="{BASE}embed.js" async&gt;&lt;/script&gt;'
    langs_options = "".join(f'<option value="{l}">{e(t["lang_names"][l])}</option>' for l in LANGS)
    level_options = "".join(f'<option value="{k}">{e(v)}</option>' for k, v in t["levels"].items())
    switcher = " · ".join(
        f'<a href="{FILE[l]}" hreflang="{l}" lang="{l}"' + (' aria-current="page"' if l == lang else "") + f'>{NATIVE[l]}</a>'
        for l in LANGS)
    alternates = "\n".join(f'<link rel="alternate" hreflang="{l}" href="{BASE}{FILE[l]}">' for l in LANGS)
    values = dict(t)
    values.update(
        lang=lang, base=BASE, host=HOST, app=APP, host_code=host_code, game_title=GAME_TITLE[lang],
        langs_options=langs_options, level_options=level_options, switcher=switcher, alternates=alternates,
        p_host=t["p_host"].format(host=HOST_NAME), s3=t["s3"].format(host=HOST_NAME),
        medium=t["levels"]["medium"])
    out = TEMPLATE
    for key, value in values.items():
        if isinstance(value, str):
            out = out.replace("{{" + key + "}}", value)
    assert "{{" not in out, out[out.index("{{"):out.index("{{") + 40]
    return out


if __name__ == "__main__":
    daily = pathlib.Path(__file__).resolve().parent.parent / "daily"
    for lang in LANGS:
        (daily / FILE[lang]).write_text(build(lang), encoding="utf-8")
        print("wrote", FILE[lang])
